# Generated by Django 3.1.7 on 2021-03-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20210312_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peers',
            new_name='Folks',
        ),
    ]
