# Generated by Django 3.1.7 on 2021-03-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20210312_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folks',
            new_name='Peer',
        ),
    ]
