# Generated by Django 3.1.7 on 2021-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20210312_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='peer',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
