# Generated by Django 3.1.7 on 2021-03-13 06:45

from django.db import migrations, models
import logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_auto_20210312_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Peer',
        ),
    ]
