# Generated by Django 3.1.7 on 2021-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20210314_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
